### ISSUE TITLE
RGB Ring Service root preventing pi from running example

### ISSUE THREAD

**Issue by nubcore** [ubopod/ubo-sdk#1]
Setup the RGB service per README, this causes the example to fail when run without sudo because there is an error when trying to access error.log which requires root. Changing error.log to pi as group with write permission fixes.

Also typo in service cp command, '/' not needed. Also usually use sequence, systemctl start first to test that everything is working, if so then systemctl enable.

**Comment by ubopod** [comment]
thanks for opening the issue :) I pushed a messy code. I am going to put untested code on dev branch and keep fully tested code on main

**Comment by nubcore** [comment]
Excellent, mostly pushing buttons to figure out flow for async collab

**Comment by nubcore** [comment]
Ok, so pushing the button next to comment does the thing, and down arrow changes the thing. Now pushing the "Comment" button as intended, will leave as is, if you want it to re-open for tracking, understood work in progress. Maybe we want to create a task for working out the overall game plan on setting up services and managing privileges.

**Comment by ubopod** [comment]
FYI, we have dev branch now. let's push all codes changes to dev and test befoe merging into min

**Comment by ubopod** [comment]
I think I need to convert to an organization for better workflow management. let's figure this out on Friday. with cp command, I am copying into a system/ directory (sudo cp rgb-ring.service /etc/systemd/system/). If I remove that it would copy to system as a file
