### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by nubcore** [ubopod/ubo-sdk#3]
Exclude __pycache__ and other directories/files?

**Comment by ubopod** [comment]
They are already excluded in the .gitignore file. However, one of the .pyc file is still being tracked for me. I don't know why

```
# Byte-compiled / optimized / DLL files
__pycache__/
*/__pycache__/
*/*/__pycache__/
*/*/*/__pycache__/
*.cpython-39.pyc
*.py[cod]
*$py.class
```

**Comment by ubopod** [comment]
it's `lcd..cpython-39.pyc`

**Comment by ubopod** [comment]
I removed this from from dev branch. it's now not being tracked.
